---
- name: 'Include pgarchives role with variables for _private'
  include_role:
    name: pgarchives
  vars:
    database_name_pgarchives: '{{ database_name_pgarchives_private }}'
    service_vhost_name_pgarchives: '{{ service_vhost_name_pgarchives_private }}'
    base_path_pgarchives: '{{ base_path_pgarchives_private }}'
    pgarchives_private: 'True'
