---
- name: 'Add PGDG signing key'
  apt_key:
    url: 'https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc'
    state: 'present'

- name: 'Configure pgdg repositories'
  apt_repository:
    repo: 'deb https://apt.postgresql.org/pub/repos/apt {{ debian_version }}-pgdg main'
    state: 'present'
    filename: 'pgdg'

- name: 'Setup apt-preferences for PGDG'
  copy:
    dest: '/etc/apt/preferences.d/pgdg-pin'
    content: |
      Package: postgresql*
      Pin: origin "apt.postgresql.org"
      Pin-Priority: 900
    owner: 'root'
    group: 'root'
    mode: 0640

- name: 'Install postgresl'
  package:
    name:
      - 'postgresql'
      - 'postgresql-client'
    state: 'latest'

- name: 'Copy connection file for postgresql'
  copy:
    src: 'pg_hba.conf'
    dest: '/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'
    owner: 'postgres'
    group: 'postgres'
    mode: 0640
  notify: 'restart postgresql'

- include: "pgbackrest.yml"
  when: install_pgbackrest is defined and install_pgbackrest == True
