---

- name: 'Restart postgresql'
  block:
    - name: 'Restart postgresql (systemd)'
      service:
        name: 'postgresql@{{ postgresql_version }}-main'
        state: 'restarted'
      ignore_errors: true
      register: systemd

    - name: 'Restart postgresql (sysvinit)'
      service:
        name: 'postgresql'
        state: 'restarted'
      when: systemd.failed
