---

- name: 'Restart postgresql'
  block:
  - name: 'Ensure postgresql is enabled/started (systemd)'
    service:
      name: 'postgresql@{{ postgresql_version }}-main'
      state: 'restarted'
      enabled: true
    ignore_errors: true
    register: systemd

  - name: 'Ensure postgresql is enabled/started (sysvinit)'
    service:
      name: 'postgresql'
      state: 'restarted'
      enabled: true
    when: systemd.failed
