---
- name: Main playbook to install pglister, pgarchives, pgarchives-private, configure exim4, httpd and postgresql
  hosts: all
  become: true

  vars_files:
    - vars/gitlab-ci.yml

  roles:
    - {role: 'exim_pglister', tags: 'exim_pglister'}
    - {role: 'pgweb', tags: 'pgweb'}
    - {role: 'pglister', tags: 'pglister'}
    - {role: 'pgarchives', tags: 'pgarchives'}
    - {role: 'pgarchives_private', tags: 'pgarchives_private'}
