---
# Apt conf
- name: 'Apt Configuration'
  template:
    src: '{{ item }}.j2'
    dest: '/etc/apt/apt.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'local-recommends'
    - 'local-pdiffs'
    - 'local-aptitude'
  notify: 'apt update'

- set_fact:
    apt_packages:
      - 'unattended-upgrades'
      - 'apt-listchanges'

- name: 'Install packages'
  apt:
    name: '{{ packages + apt_packages }}'
    state: 'latest'
    update_cache: true

- name: 'Ensure unattended-upgrades is started and enabled'
  service:
    name: 'unattended-upgrades'
    state: 'started'
    enabled: true
