---
dependencies:
  - { role: 'postgresql', when: redeploy == False, tags: 'postgresql' }
  - { role: 'exim_pglister', when: redeploy == False, tags: ['exim_pglister', 'exim-pglister'] }

galaxy_info:
  author: 'Célestin Matte'
  description: Installs PGLister, the mailinglist system
  company: SPI
  issue_tracker_url: https://gitlab.com/cmatte/ansible-pglister/-/issues
  license: GPL-2.0-or-later
  min_ansible_version: 2.11.12
  platforms:
    - name: Debian
      versions:
        - 'bullseye'
        - 'bookworm'
  galaxy_tags: ['pglister', 'mailinglist']
