---

- fail:
    msg: 'Please fill the service_vhost_name variable'
  when: service_vhost_name|length == 0

- set_fact:
    le_domains: '{{ le_domains + [service_vhost_name] + service_vhost_aliases }}'

- name: 'Drop apache restart script'
  copy:
    content: "#!/bin/sh\n\nsystemctl restart apache2\n"
    dest: '{{ le_deploy_hooks_path }}/apache2.sh'
    owner: 'root'
    group: 'root'
    mode: 0755

- name: 'Create log folder'
  file:
    path: '{{ log_path }}'
    state: 'directory'
    owner: 'list'
    group: 'www-data'
    mode: 0755
  notify: 'reload httpd'

- name: 'Drop vhost template for {{ service_vhost_name }}'
  template:
    src: 'vhost.conf.j2'
    dest: '/etc/apache2/sites-available/{{ service_vhost_priority }}-{{ service_vhost_name }}.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'reload httpd'

# TODO: Ensure unneeded vhosts are disabled.
- name: 'Enable vhost {{ service_vhost_name }}'
  command: '/usr/sbin/a2ensite {{ service_vhost_priority }}-{{ service_vhost_name }}'
  notify: 'reload httpd'
