cron_emails_destination: 'root'

# same as for letsencrypt role
le_cert_dir: '/etc/ssl/certs'
le_key_dir: '/etc/ssl/private'
le_cert_path: '{{ le_cert_dir }}/{{ ansible_host }}.pem'
le_key_path: '{{ le_key_dir }}/{{ ansible_host }}.key'
