---
# This variable is supposed to be filled by various roles beforehand
le_domains: ['{{ service_vhost_name_pgweb }}', '{{ service_vhost_name_pglister }}', '{{ service_vhost_name_pgarchives }}', '{{ service_vhost_name_pgarchives_private }}']

le_email: 'postmaster@{{ domain }}'
le_webroot: '/srv/letsencrypt/'
# Also defined in http_vhost role. We have to define it here as well since
# including role does not import variables
le_deploy_hooks_path: '/srv/letsencrypt/hooks'
le_cert_dir: '/etc/ssl/certs'
le_key_dir: '/etc/ssl/private'
le_cert_path: '{{ le_cert_dir }}/{{ ansible_host }}.pem'
le_key_path: '{{ le_key_dir }}/{{ ansible_host }}.key'
