---
service_vhost_name: '{{ service_vhost_name_pgarchives }}'
repo_name: 'pgarchives.git'
# repo_uri: 'https://github.com/postgres/{{ repo_name }}'
repo_uri: 'https://gitlab.com/cmatte/{{ repo_name }}'
base_path: '{{ base_path_pgarchives }}'
service_base_path: '{{ base_path }}/local'
web_path: '{{ base_path }}/local/django/archives'
repo_path: '{{ base_path }}/{{ repo_name }}'
venv_python: '{{ service_base_path }}/django/bin/python'

admin_email_address: 'webmaster@{{ domain }}'
pgarchives_django_secret_key: 'changemechangeme!-ansible'
python_version: '{{ "python3.7" if debian_version == "buster" else "python3.11" }}'
