---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-debian10-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    etc_hosts: >-
      {
      "pgweb.localhost pglister.localhost pgarchives.localhost pgarchives-private.localhost": "127.0.0.1"
      }
provisioner:
  name: ansible
verifier:
  name: ansible
