---
- name: Verify
  hosts: all

  tasks:
    - name: Check if pglister is running
      uri:
        url: https://pglister.localhost
        validate_certs: false
        return_content: true
      register: pglister_content
      failed_when: "'From this site you can manage all your' not in pglister_content.content"

    - name: Check if pgweb is running
      uri:
        url: https://pgweb.localhost
        validate_certs: false
        return_content: true
        follow_redirects: true
      register: pgweb_content
      failed_when: "'Community account sign-in' not in pgweb_content.content"

    - name: Check if pgarchives is running
      uri:
        url: https://pgarchives.localhost
        validate_certs: false
        return_content: true
      register: pgarchives_content
      failed_when: "'View All Archives' not in pgarchives_content.content"

    - name: Check if pgarchives-private is running
      uri:
        url: https://pgarchives-private.localhost
        validate_certs: false
        return_content: true
      register: pgarchives_private_content
      failed_when: "'The website you are trying to log in to (pgarchives_private) is using the\npostgresql.org community login system' not in pgarchives_private_content.content"
