---
- name: 'Install httpd'
  package:
    name: 'apache2'
    state: 'present'

- name: 'Install python-passlib to create htpassword, if necessary'
  package:
    name: 'python3-passlib'
    state: 'present'
  when: not production

- name: 'Drop default templates'
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - { src: '000-default.conf', dest: '/etc/apache2/sites-available/000-default.conf' }
    - { src: 'ssl.conf', dest: '{{ httpd_ssl_conf }}' }
    - { src: 'mod_ssl.conf', dest: '/etc/apache2/mods-available/ssl.conf' }
  notify: 'Reload httpd'

- name: 'Remove ssl-cert vhost'
  file:
    path: '/etc/apache2/sites-available/default-ssl.conf'
    state: 'absent'

# Necessary to enable modules, otherwise apache crashes
- name: 'Disable "000-default" vhost'
  command: '/usr/sbin/a2dissite 000-default'
  ignore_errors: true

- name: 'Enable modules'
  community.general.apache2_module:
    name: '{{ item }}'
    state: present
  with_items:
    - 'headers'
    - 'rewrite'
    - 'ssl'
  notify: 'Reload httpd'

- name: 'Enable Apache auth modules'
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - auth_basic
    - authn_file
  when: not production

- name: 'Enable proxy module'
  when: httpd_proxy | default(false)
  community.general.apache2_module:
    name: 'proxy'
    state: present
  notify: 'Reload httpd'

- name: 'Enable default vhost'
  command: '/usr/sbin/a2ensite 000-default'
  register: result
  changed_when: 'not "already enabled" in result.stdout'
  notify: 'Reload httpd'

- name: 'Set ServerTokens'
  lineinfile:
    path: '/etc/apache2/conf-available/security.conf'
    regexp: '^ServerTokens'
    line: 'ServerTokens Prod'
  notify: 'Reload httpd'

- name: 'Create the .htpasswd file with user credentials'
  community.general.htpasswd:
    path: /etc/apache2/.htpasswd
    name: "{{ http_auth_username }}"
    password: "{{ http_auth_password }}"
    crypt_scheme: bcrypt
    mode: '640'
    group: 'www-data'
  when: not production

# Ensure certificates are present before starting the server.

- name: 'Ensure httpd is started'
  service:
    name: 'apache2'
    state: 'started'
    enabled: true
