---
- include_role:
    name: 'letsencrypt'
  when: 'use_letsencrypt is defined and use_letsencrypt'

- name: 'Install httpd'
  package:
    name: 'apache2'
    state: 'latest'

- name: 'Disable "000-default" vhost'
  command: '/usr/sbin/a2dissite 000-default'
  register: result
  changed_when: 'not "already enabled" in result.stdout'
  notify: 'reload httpd'
  ignore_errors: true

- name: 'Drop default templates'
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - { src: '090-default.conf', dest: '/etc/apache2/sites-available/090-default.conf' }
    - { src: 'ssl.conf', dest: '{{ httpd_ssl_conf }}' }
    - { src: 'mod_ssl.conf', dest: '/etc/apache2/mods-available/ssl.conf' }
  notify: 'reload httpd'

- name: 'Remove ssl-cert vhost'
  file:
    path: '/etc/apache2/sites-available/default-ssl.conf'
    state: 'absent'

- name: 'Enable modules'
  command: '/usr/sbin/a2enmod {{ item }}'
  loop:
    - 'headers'
    - 'rewrite'
    - 'ssl'
  register: result
  changed_when: 'not "already enabled" in result.stdout'
  notify: 'reload httpd'

- name: 'Enable default vhost'
  command: '/usr/sbin/a2ensite 090-default'
  register: result
  changed_when: 'not "already enabled" in result.stdout'
  notify: 'reload httpd'

- name: 'Set ServerTokens'
  lineinfile:
    path: '/etc/apache2/conf-available/security.conf'
    regexp: '^ServerTokens'
    line: 'ServerTokens Prod'
  notify: 'reload httpd'

# Ensure certificates are present before starting the server.

- name: 'Ensure httpd is started'
  service:
    name: 'apache2'
    state: 'started'
    enabled: true
