---
galaxy_info:
  author: 'Maxime Buquet (pep), Célestin Matte'
  description: A basic role to install postgresql, for PGlister
  company: SPI
  issue_tracker_url: https://gitlab.com/cmatte/ansible-pglister/-/issues
  license: GPL-2.0-or-later
  min_ansible_version: 2.11.12
  platforms:
    - name: Debian
      versions:
        - 'buster'
  galaxy_tags: ['pglister', 'mailinglist']
