---
- name: 'Create folder tree'
  file:
    path: '{{ service_base_path }}'
    state: 'directory'
    owner: 'list'
    group: 'www-data'
    mode: '755'

- name: 'Clone pglister repository'
  git:
    repo: '{{ repo_uri }}'
    dest: '{{ base_path }}/{{ repo_name }}'
    clone: true
    update: true
    version: '{{ pglister_version }}'
  register: repo

- name: 'Copy repository content to local folder'
  command:
    cmd: sh -c 'cp -r {{ base_path }}/{{ repo_name }}/* {{ service_base_path }}/'

- name: 'Chown list:www-data pglister directory'
  file:
    path: '{{ service_base_path }}'
    owner: 'list'
    group: 'www-data'
    recurse: true

- name: 'Override home.html to remove mentions of postgresql.org'
  template:
    src: 'home.html.j2'
    dest: '{{ service_base_path }}/web/pglister/lists/templates/home.html'
    owner: 'list'
    group: 'www-data'
    mode: '644'

- name: 'Copy pglister config'
  template:
    src: 'pglister.ini.j2'
    dest: '{{ service_base_path }}/pglister.ini'
    owner: 'list'
    group: 'www-data'
    mode: '664'

- name: 'Drop settings.py for django'
  template:
    src: 'settings.py.j2'
    dest: '{{ service_base_path }}/web/pglister/local_settings.py'
    owner: 'list'
    group: 'www-data'
    mode: '640'

- name: 'Add link to venv to systemd services'
  lineinfile:
    path: '{{ service_base_path }}/systemd/pglister_{{ item }}.template'
    regexp: '^ExecStart=_ROOT_'
    line: 'ExecStart={{ venv_python }} _ROOT_/bin/{{ item }}.py'
  loop:
    - 'bounceprocessor'
    - 'cleanup'
    - 'eximcleaner'
    - 'mailprocessor'
    - 'mailsender'
    - 'moderationprocessor'
