---
- name: 'Override home.html to remove mentions of postgresql.org'
  template:
    src: 'home.html.j2'
    dest: '{{ service_base_path }}/web/pglister/lists/templates/home.html'
    owner: 'list'
    group: 'www-data'
    mode: '644'

- name: 'Copy pglister config'
  template:
    src: 'pglister.ini.j2'
    dest: '{{ service_base_path }}/pglister.ini'
    owner: 'list'
    group: 'www-data'
    mode: '664'
  notify: 'Restart systemd services'

- name: 'Drop settings.py for django'
  template:
    src: 'settings.py.j2'
    dest: '{{ service_base_path }}/web/pglister/local_settings.py'
    owner: 'list'
    group: 'www-data'
    mode: '640'

- name: 'Loop over services to properly edit them'
  include_tasks: 'service_override.yml'
  loop:
    - 'bounceprocessor'
    - 'cleanup'
    - 'eximcleaner'
    - 'mailprocessor'
    - 'mailsender'
    - 'moderationprocessor'
  loop_control:
    loop_var: service_name
