---
database_user_pgarchives: 'list'
database_name_pgarchives: 'pgarchives'
pgarchives_version: '04b577002aa4550b8fb3113feff0021bd35dfb5e'
debug: false
logging_level: 'ERROR'
redeploy: false
# If set to true, pglister_sync won't be executed (not necessary for gitlab-ci)
test_only: false
# Will skips some steps in case application is deployed without
# correct DNS setup
pre_deployment: false
