---
repo_name: 'pglister.git'
repo_base: 'cmatte'
repo_uri: 'https://gitlab.com/{{ repo_base }}/{{ repo_name }}'
base_path: '{{ base_path_pglister }}'
service_base_path: '{{ base_path }}/local'
external_url: 'https://{{ service_vhost_name }}'
venv_python: '{{ service_base_path }}/web/pglister/bin/python'

confirm_sender_address: 'confirmsender@{{ domain }}'
pglister_django_secret_key: 'changemechangeme!-ansible'
service_vhost_name: '{{ service_vhost_name_pglister }}'
python_version: '{{ "python3.7" if debian_version == "buster" else "python3.11" }}'
