---
repo_name: 'pglister.git'
repo_uri: 'https://gitlab.com/cmatte/{{ repo_name }}'
base_path: '/srv/pglister'
service_base_path: '{{ base_path }}/local'
external_url: 'https://{{ service_vhost_name }}'

confirm_sender_address: 'confirmsender@{{ domain }}'
django_secret_key: 'changemechangeme!-ansible'
service_vhost_name: '{{ service_vhost_name_pglister }}'
