---
- name: 'Install required packages'
  package:
    state: 'present'
    name:
      - 'python3'
      - 'git'
      - 'libapache2-mod-wsgi-py3'
      - 'python3-pip'
      - 'python3-psycopg2'
      - 'python3-virtualenv'
      - 'virtualenv'
      - 'postgresql-contrib'
  when: not redeploy

- name: 'Postresql queries'
  import_tasks: postgresql_queries.yml
  become: true
  become_user: 'postgres'
  when: not redeploy
  notify: 'Restart postgresql'

- name: 'Include role http_vhost'
  include_role:
    name: 'http_vhost'
  vars:
    service_vhost_extra: true
    http_vhost_app_user: '{{ app_user }}'
  when: not redeploy

# ignore_configcheck prevents module from crashing
- name: 'Activate mod_wsgi on apache2'
  community.general.apache2_module:
    name: wsgi
    state: present
    ignore_configcheck: true
  notify: 'Reload httpd'
  when: not redeploy

- name: 'Clone repository'
  git:
    repo: '{{ repo_uri }}'
    dest: '{{ app_base_path }}/repo.git'
    clone: true
    update: true
    version: '{{ app_version }}'
  become: true
  become_user: '{{ app_user }}'
  register: repo

- name: 'Copy repository to folder used by apache2'
  ansible.builtin.copy:
    src: '{{ app_base_path }}/repo.git/'
    dest: '{{ app_service_base_path }}/'
    mode: '755'
    remote_src: true
  when: repo.changed  # noqa: no-handler

- name: 'Chown app_user:www-data app directory'
  file:
    path: '{{ app_service_base_path }}'
    owner: '{{ app_user }}'
    group: 'www-data'
    recurse: true
  when: repo.changed  # noqa: no-handler

- name: 'Install required packages for ansible using pip'
  pip:
    name:
      - '{{ psycopg_version }}'
      - '{{ pycryptodomex_version }}'
    virtualenv: '{{ app_virtualenv }}'
    virtualenv_python: python3
  become: true
  become_user: '{{ app_user }}'

- name: 'Install python dependencies from requirements.txt'
  ansible.builtin.pip:
    requirements: '{{ requirements_path }}/requirements.txt'
    virtualenv: '{{ app_virtualenv }}'
    virtualenv_python: python3
  become: true
  become_user: '{{ app_user }}'
  when: 'requirements_path is defined'
