---
- name: 'Create database'
  community.postgresql.postgresql_db:
    name: '{{ database_name }}'

- name: 'Create role for database_user'
  community.postgresql.postgresql_user:
    name: '{{ database_user }}'
    password: '{{ database_password }}'

# GRANT ALL ON DATABASE {{ database_name }} TO "{{ database_user }}";'
- name: 'Grant database privileges to user'
  community.postgresql.postgresql_privs:
    db: '{{ database_name }}'
    privs: 'ALL'
    type: 'database'
    objs: '{{ database_name }}'
    role: '{{ database_user }}'

# GRANT CREATE ON SCHEMA public TO "{{ database_user }}";'
- name: 'Grant CREATE on schema public to user'
  community.postgresql.postgresql_privs:
    db: '{{ database_name }}'
    privs: 'CREATE'
    type: 'schema'
    objs: 'public'
    role: '{{ database_user }}'
  register: user_privs

# GRANT ALL ON ALL TABLES IN SCHEMA public TO "{{ database_user }}";'
- name: 'Grant all privileges on all tables in public schema to user'
  community.postgresql.postgresql_privs:
    db: '{{ database_name }}'
    privs: 'ALL'
    type: 'table'
    objs: 'ALL_IN_SCHEMA'
    role: '{{ database_user }}'
    schema: 'public'
  # Ugly hack to fix idempotency because postgresql_privs fails at properly
  # returning changed status
  when: user_privs.changed  # noqa: no-handler

# GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "{{ database_user }}";'
- name: 'Grant all privileges on all sequences in public schema to user'
  community.postgresql.postgresql_privs:
    db: '{{ database_name }}'
    privs: 'ALL'
    type: 'sequence'
    objs: 'ALL_IN_SCHEMA'
    role: '{{ database_user }}'
    schema: 'public'
  # Ugly hack to fix idempotency because postgresql_privs fails at properly
  # returning changed status
  when: user_privs.changed  # noqa: no-handler
